Repository jolocom/smartwallet-app, pull requests merged in 2018-03, with the labels that each got.

#935 Pass arguments as an object to verified claim method on JolocomLib
  package.json
  src/js/redux_state/modules/wallet/identity-new.js
Labels: ready

#954 Add Pull Request template
  PULL_REQUEST_TEMPLATE.md
Labels: finished

#956 Removed unreliable encryption logic. Will be reimplemented after furt…
  app/config.xml
  app/package.json
  package-lock.json
  src/js/redux_state/modules/registration.js
  src/js/redux_state/modules/registration.test.js
  src/js/redux_state/modules/single-sign-on/access-request.js
  src/js/services/storage.js
Labels: bug, finished

#957 SSO confirmation loading screen
  app/config.xml
  src/js/components/single-sign-on/presentation/access-request.jsx
  src/js/components/wallet/presentation/home.jsx
  src/js/redux_state/modules/single-sign-on/access-request.js
Labels: bug, code review required, finished

#948 Changed config file to route IPFS requests to Jolocom IPFS node
  app/config.xml
  app/package.json
  package-lock.json
  package.json
  src/js/redux_state/create.js
Labels: code review required, finished
