Repository jolocom/smartwallet-app, pull requests merged in 2018-04, with the labels that each got.

#974 Feature/961 entropy collection
  .gitignore
  .travis.yml
  android/.gradle/2.14.1/taskArtifacts/cache.properties
  android/.gradle/2.14.1/taskArtifacts/cache.properties.lock
  android/.gradle/2.14.1/taskArtifacts/fileHashes.bin
  android/.gradle/2.14.1/taskArtifacts/fileSnapshots.bin
  android/.gradle/2.14.1/taskArtifacts/fileSnapshotsToTreeSnapshotsIndex.bin
  android/.gradle/2.14.1/taskArtifacts/taskArtifacts.bin
  android/.gradle/2.14.1/tasks/_app_compileDebugJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.bin
  android/.gradle/2.14.1/tasks/_app_compileDebugJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.lock
  android/.gradle/2.14.1/tasks/_app_compileDebugJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.bin
  android/.gradle/2.14.1/tasks/_app_compileDebugJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.lock
  android/.gradle/2.14.1/tasks/_react-native-keychain_compileReleaseJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.bin
  android/.gradle/2.14.1/tasks/_react-native-keychain_compileReleaseJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.lock
  android/.gradle/2.14.1/tasks/_react-native-keychain_compileReleaseJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.bin
  android/.gradle/2.14.1/tasks/_react-native-keychain_compileReleaseJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.lock
  android/.gradle/2.14.1/tasks/_react-native-vector-icons_compileReleaseJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.bin
  android/.gradle/2.14.1/tasks/_react-native-vector-icons_compileReleaseJavaWithJavac/localClassSetAnalysis/localClassSetAnalysis.lock
  android/.gradle/2.14.1/tasks/_react-native-vector-icons_compileReleaseJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.bin
  android/.gradle/2.14.1/tasks/_react-native-vector-icons_compileReleaseJavaWithJavac/localJarClasspathSnapshot/localJarClasspathSnapshot.lock
  android/app/build.gradle
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/java/com/smartwallet/MainApplication.java
  android/settings.gradle
  ios/smartwallet.xcodeproj/project.pbxproj
  ios/smartwallet.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/smartwallet.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/smartwallet.xcodeproj/project.xcworkspace/xcuserdata/charly.xcuserdatad/UserInterfaceState.xcuserstate
  ios/smartwallet.xcodeproj/xcuserdata/charly.xcuserdatad/xcschemes/xcschememanagement.plist
  package.json
  src/actions/navigation/index.ts
  src/actions/registration/index.ts
  src/lib/entropyGenerator.ts
  src/reducers/index.ts
  src/routes.ts
  src/styles/jolocom-theme.ts
  src/ui/landing/components/landing.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/registration/components/entropy.tsx
  src/ui/registration/components/maskedImage.tsx
  src/ui/registration/containers/entropy.tsx
  src/ui/registration/containers/passwordEntry.tsx
  src/ui/registration/index.ts
  tests/App.test.tsx
  tests/lib/entropyGenerator.test.ts
  tests/ui/components/__snapshots__/entropy.test.tsx.snap
  tests/ui/components/__snapshots__/maskedImage.test.tsx.snap
  tests/ui/components/__snapshots__/passwordEntry.test.tsx.snap
  tests/ui/components/__snapshots__/seedPhrase.test.tsx.snap
  tests/ui/components/entropy.test.tsx
  tests/ui/components/maskedImage.test.tsx
  tests/ui/components/passwordEntry.test.tsx
  tests/ui/components/seedPhrase.test.tsx
  tests/ui/containers/__snapshots__/entropy.test.tsx.snap
  tests/ui/containers/entropy.test.tsx
  tests/ui/containers/passwordEntry.test.tsx
  tests/ui/containers/seedPhrase.test.tsx
  tests/utils/setup.ts
Labels: in progress, porting to React Native

#979 Importing of React library
  src/App.tsx
  src/NavigatorContainer.tsx
  src/ui/home/containers/Home.tsx
  src/ui/landing/components/landing.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/registration/components/entropy.tsx
  src/ui/registration/components/maskedImage.tsx
  src/ui/registration/components/passwordEntry.tsx
  src/ui/registration/components/seedPhrase.tsx
  src/ui/registration/containers/entropy.tsx
  src/ui/registration/containers/passwordEntry.tsx
  src/ui/registration/containers/seedPhrase.tsx
  src/ui/structure/block.tsx
  src/ui/structure/centeredText.tsx
  src/ui/structure/container.tsx
  src/ui/structure/header.tsx
  src/ui/structure/index.tsx
  tests/App.test.tsx
  tests/lib/keyChain.test.ts
  tests/ui/components/entropy.test.tsx
  tests/ui/components/maskedImage.test.tsx
  tests/ui/components/passwordEntry.test.tsx
  tests/ui/components/seedPhrase.test.tsx
  tests/ui/containers/entropy.test.tsx
  tests/ui/containers/passwordEntry.test.tsx
  tests/ui/containers/seedPhrase.test.tsx
  tests/ui/structure/block.test.tsx
  tests/ui/structure/centeredText.test.tsx
  tests/ui/structure/container.test.tsx
Labels: code review required, finished

#981 Feature/980 nav bar
  package.json
  src/NavigatorContainer.tsx
  src/routes.ts
  src/ui/home/components/identity.tsx
  src/ui/home/components/interactions.tsx
  src/ui/home/containers/Home.tsx
  src/ui/home/containers/identity.tsx
  src/ui/home/containers/interactions.tsx
  src/ui/home/index.tsx
  src/ui/registration/components/seedPhrase.tsx
  tests/reducers/navigation/index.test.ts
  tests/ui/containers/entropy.test.tsx
Labels: code review required, finished, porting to React Native

#987 Feature/982 identity screen wireframe
  package.json
  src/routes.ts
  src/styles/jolocom-theme.ts
  src/ui/home/components/identity.tsx
  src/ui/home/containers/identity.tsx
  tests/reducers/navigation/index.test.ts
Labels: feature, porting to React Native

#985 Feature/#984 svg handling for release build
  android/app/build.gradle
  package-lock.json
  package.json
  src/img/img_onboarding-00.svg
  src/img/img_onboarding-01.svg
  src/img/img_onboarding-02.svg
  src/img/img_onboarding-03.svg
  src/img/img_onboarding-04.svg
  src/img/img_onboarding-05.svg
  src/resources/img/img_techguy.svg
  src/resources/img/logo.png
  src/resources/index.ts
  src/resources/svg/Onboarding00.js
  src/resources/svg/Onboarding01.js
  src/resources/svg/Onboarding02.js
  src/resources/svg/Onboarding03.js
  src/resources/svg/Onboarding04.js
  src/resources/svg/Onboarding05.js
  src/resources/svg/Techguy.js
  src/ui/landing/components/landing.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/registration/components/seedPhrase.tsx
  tests/assetsTransformer.js
  tests/ui/components/__snapshots__/landing.test.tsx.snap
  tests/ui/components/__snapshots__/seedPhrase.test.tsx.snap
  tests/ui/components/landing.test.tsx
  tests/ui/containers/__snapshots__/landing.test.tsx.snap
  tests/ui/containers/landing.test.tsx
Labels: code review required, porting to React Native

#991 Feature/#990 upgrade gradle version
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
Labels: code review required

#993 Feature/#952 client storage implementation
  .gitignore
  android/app/build.gradle
  android/app/src/main/java/com/smartwallet/MainApplication.java
  android/settings.gradle
  ios/smartwallet.xcodeproj/project.pbxproj
  ios/smartwallet.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/smartwallet.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/smartwallet.xcodeproj/project.xcworkspace/xcuserdata/charly.xcuserdatad/UserInterfaceState.xcuserstate
  ios/smartwallet.xcodeproj/xcshareddata/xcschemes/smartwallet-tvOS.xcscheme
  ios/smartwallet.xcodeproj/xcshareddata/xcschemes/smartwallet.xcscheme
  ios/smartwallet.xcodeproj/xcuserdata/charly.xcuserdatad/xcschemes/xcschememanagement.plist
  package.json
  src/lib/dbHelper.ts
  src/lib/keychain.ts
  src/lib/storage.ts
  src/ui/landing/containers/landing.tsx
  tests/__snapshots__/App.test.tsx.snap
  tests/lib/__snapshots__/dbHelper.test.ts.snap
  tests/lib/__snapshots__/storage.test.ts.snap
  tests/lib/dbHelper.test.ts
  tests/lib/storage.test.ts
  tests/lib/testData/storageTestData.ts
Labels: code review required, feature, porting to React Native
