Repository jolocom/smartwallet-app, pull requests merged in 2018-06, with the labels that each got.

#1048 Fix/1032 navigation back arrow
  src/actions/account/index.ts
  src/actions/navigation/index.ts
  src/actions/registration/index.ts
  src/routeList.ts
  src/ui/home/components/identity.tsx
  tests/actions/account/__snapshots__/index.test.ts.snap
Labels: code review required, finished

#1050 added conditional to styling of continue button for Password Screen
  src/reducers/navigation/index.ts
  src/ui/registration/components/passwordEntry.tsx
  tests/ui/components/__snapshots__/passwordEntry.test.tsx.snap
Labels: UI/Styling, code review required, finished

#1051 Fix/1042 entropy continue button
  src/ui/registration/components/entropy.tsx
  tests/ui/components/__snapshots__/entropy.test.tsx.snap
Labels: UI/Styling, code review required, finished

#1057 Changed colors, updated snapshots to reflect new UI
  src/ui/generic/loading.tsx
  src/ui/landing/components/landing.tsx
  tests/ui/components/__snapshots__/landing.test.tsx.snap
Labels: UI/Styling, code review required, finished

#1054 Fix/1053 placeholder tab
  package.json
  src/reducers/navigation/index.ts
  src/routeList.ts
  src/routes.ts
  src/ui/home/components/interactions.tsx
  yarn.lock
Labels: code review required, finished

#1034 Feature/#1020 ui claim entry
  package.json
  src/actions/account/categories.ts
  src/actions/account/index.ts
  src/reducers/account/claims.ts
  src/reducers/account/index.ts
  src/resources/img/close.png
  src/routeList.ts
  src/routes.ts
  src/ui/home/components/claimCard.tsx
  src/ui/home/components/claimDetails.tsx
  src/ui/home/components/claimOverview.tsx
  src/ui/home/components/textInputField.tsx
  src/ui/home/containers/claimDetails.tsx
  src/ui/home/containers/claims.tsx
  src/ui/home/index.tsx
  tests/reducers/accounts/__snapshots__/index.test.ts.snap
  tests/ui/components/__snapshots__/claimCard.test.tsx.snap
  tests/ui/components/__snapshots__/claimOverview.test.tsx.snap
  tests/ui/components/claimCard.test.tsx
  tests/ui/components/claimOverview.test.tsx
  tests/ui/containers/__snapshots__/claims.test.tsx.snap
  tests/ui/containers/claims.test.tsx
  tsconfig.json
Labels: code review required, feature, finished

#1058 Splashscreen + Icons
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/smartwallet/MainActivity.java
  android/app/src/main/java/com/smartwallet/MainApplication.java
  android/app/src/main/java/com/smartwallet/SplashActivity.java
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/icon.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/icon.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/icon.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/icon.png
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/settings.gradle
  src/App.tsx
Labels: UI/Styling, code review required, finished

#1061 changed name of app to Jolocom
  android/app/src/main/res/values/strings.xml
Labels: code review required, finished

#1064 fix/android-package-name
  android/app/build.gradle
Labels: code review required

#1062 Save retrieve claims from db
  package.json
  src/actions/account/index.ts
  src/actions/sso/index.ts
  src/lib/storage/entities/verifiableCredentialEntity.ts
  src/lib/storage/storage.ts
  src/reducers/account/claims.ts
  src/ui/home/components/claimCard.tsx
  src/ui/home/components/claimDetails.tsx
  src/ui/home/containers/claimDetails.tsx
  src/ui/home/index.tsx
  src/ui/sso/components/attributeSelectionSection.tsx
  tests/reducers/accounts/__snapshots__/index.test.ts.snap
  tests/ui/components/__snapshots__/claimCard.test.tsx.snap
  yarn.lock
Labels: code review required

#1065 Consistent fonts
  src/routes.ts
  src/styles/jolocom-theme.ts
  src/ui/generic/exception.tsx
  src/ui/home/components/claimCard.tsx
  src/ui/home/components/claimOverview.tsx
  src/ui/home/components/textInputField.tsx
  src/ui/landing/components/landing.tsx
  src/ui/registration/containers/loading.tsx
  src/ui/sso/containers/consent.tsx
  tests/ui/components/__snapshots__/claimCard.test.tsx.snap
  tests/ui/components/__snapshots__/claimOverview.test.tsx.snap
  tests/ui/generic/__snapshots__/exception.test.tsx.snap
Labels: UI/Styling, finished

#1066 Added loading spinner
  src/ui/home/components/claimOverview.tsx
  tests/ui/components/__snapshots__/claimOverview.test.tsx.snap
Labels: UI/Styling, finished

#1068 fix/landing-image
  src/resources/img/02.jpg
  src/resources/img/intro-visual-01.png
  src/resources/img/intro-visual-02.png
  src/resources/img/intro-visual-03.png
  src/resources/img/intro-visual-04.png
Labels: bug, finished

#1072 Fix deny button
  src/actions/sso/index.ts
  src/ui/sso/containers/consent.tsx
Labels: bug, finished

#1070 Error handing on fuel request
  src/lib/ethereum.ts
Labels: bug, finished

#1073 Fix UI space name field
  src/ui/home/components/claimDetails.tsx
Labels: bug, finished

#1075 Arrow back claims screen
  src/actions/account/index.ts
Labels: bug, finished

#1077 Allow deselection of claims
  src/ui/sso/components/attributeSelectionSection.tsx
Labels: feature, finished

#1080 Registration process screen navigation
  src/actions/registration/index.ts
  tests/actions/registration/__snapshots__/index.test.ts.snap
Labels: bug, finished

#1081 Disabled buttons during pending action, add claim and sso
  src/ui/home/components/claimDetails.tsx
  src/ui/sso/components/consent.tsx
Labels: code review required, feature, finished

#1082 iOS custom fonts
  .babelrc
  ios/smartwallet/Info.plist
  package.json
  src/styles/jolocom-theme.android.ts
  src/styles/jolocom-theme.ios.ts
  tests/ui/components/__snapshots__/claimCard.test.tsx.snap
  tests/ui/components/__snapshots__/claimOverview.test.tsx.snap
  tests/ui/components/__snapshots__/entropy.test.tsx.snap
  tests/ui/components/__snapshots__/landing.test.tsx.snap
  tests/ui/components/__snapshots__/passwordEntry.test.tsx.snap
  tests/ui/components/__snapshots__/seedPhrase.test.tsx.snap
  tests/ui/generic/__snapshots__/exception.test.tsx.snap
  yarn.lock
Labels: UI/Styling, finished

#1084 Name entry validation
  src/ui/home/components/claimDetails.tsx
  src/ui/home/components/textInputField.tsx
  src/ui/sso/components/ssoAttributeCard.tsx
Labels: bug, code review required, finished
