Repository jolocom/smartwallet-app, pull requests merged in 2018-12, with the labels that each got.

#1174 Fix requiring images for i18n
  src/locales/i18n.ts
  src/resources/Landing00.js
  src/resources/Landing01.js
  src/resources/Landing02.js
  src/resources/Landing03.js
Labels: bug, code review required

#1179 Add address credential capability to wallet
  package.json
  src/lib/categories.ts
  src/lib/util.ts
  src/reducers/account/claims.ts
  src/ui/home/components/claimDetails.tsx
  src/ui/home/components/credentialOverview.tsx
  tests/reducers/accounts/__snapshots__/index.test.ts.snap
  yarn.lock
Labels: code review required, feature

#1182 Bottom navigation bar
  src/routes.ts
  src/ui/generic/index.ts
  src/ui/generic/layoutWithNavigationBar.tsx
  src/ui/generic/qrcodeScanner.tsx
  src/ui/home/components/credentialOverview.tsx
  src/ui/home/containers/claims.tsx
  src/ui/home/containers/interactions.tsx
  src/ui/home/containers/types.ts
  tests/ui/components/__snapshots__/layoutWithNavigationBar.test.tsx.snap
  tests/ui/components/layoutWithNavigationBar.test.tsx
  tests/ui/components/qrcodeScanner.test.tsx
  tests/ui/containers/__snapshots__/claims.test.tsx.snap
  tests/ui/containers/claims.test.tsx
Labels: feature

#1185 Feature/#1184 fixed bottom bar
  package.json
  src/NavigatorContainer.tsx
  src/styles/jolocom-theme.android.ts
  src/ui/generic/bottomActionBar.tsx
  src/ui/generic/index.ts
  src/ui/generic/layoutWithNavigationBar.tsx
  src/ui/home/containers/claims.tsx
  src/ui/home/containers/interactions.tsx
  tests/ui/components/__snapshots__/layoutWithNavigationBar.test.tsx.snap
  tests/ui/components/layoutWithNavigationBar.test.tsx
  tests/ui/containers/__snapshots__/claims.test.tsx.snap
  tests/ui/containers/__snapshots__/navigation.test.tsx.snap
  tests/ui/containers/navigation.test.tsx
  yarn.lock
Labels: code review required, feature, finished
