Repository jolocom/smartwallet-app, pull requests merged in 2018-05, with the labels that each got.

#1006 Feature/#1005 detect existing identity
  .travis.yml
  package.json
  src/actions/account/index.ts
  src/actions/registration/index.ts
  src/lib/dbHelper.ts
  src/lib/storage.ts
  src/package.json
  src/store.ts
  src/ui/home/components/identity.tsx
  src/ui/home/containers/identity.tsx
  src/ui/landing/components/landing.tsx
  src/ui/landing/containers/landing.tsx
  tests/actions/account/__snapshots__/index.test.ts.snap
  tests/actions/account/index.test.ts
  tests/actions/registration/__snapshots__/index.test.ts.snap
  tests/actions/registration/index.test.ts
  tests/lib/__snapshots__/dbHelper.test.ts.snap
  tests/lib/__snapshots__/storage.test.ts.snap
  tests/lib/dbHelper.test.ts
  tests/lib/storage.test.ts
  tests/ui/containers/__snapshots__/landing.test.tsx.snap
  tests/ui/containers/landing.test.tsx
Labels: code review required, feature, finished

#1008 Feature/#1006 tighter typing
  package.json
  src/NavigatorContainer.tsx
  src/actions/account/index.ts
  src/actions/generic/index.ts
  src/actions/registration/index.ts
  src/backendMiddleware.ts
  src/lib/crypto.ts
  src/lib/dbHelper.ts
  src/lib/ethereum.ts
  src/lib/ipfs.ts
  src/lib/keychain.ts
  src/lib/storage.ts
  src/reducers/navigation/index.ts
  src/reducers/registration/index.ts
  src/reducers/registration/loading.ts
  src/routeList.ts
  src/routes.ts
  src/store.ts
  src/ui/home/components/identity.tsx
  src/ui/home/components/qrcodeScanner.tsx
  src/ui/home/containers/identity.tsx
  tests/actions/registration/__snapshots__/index.test.ts.snap
  tests/actions/registration/data/mockRegistrationData.ts
  tests/actions/registration/index.test.ts
Labels: code review required, feature, finished

#1011 Fix the loading reducer
  src/reducers/registration/loading.ts
Labels: bug, code review required, unplanned

#1018 Feature/#1009 database claim support
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/App.tsx
  src/actions/account/index.ts
  src/actions/registration/index.ts
  src/backendMiddleware.ts
  src/lib/dbHelper.ts
  src/lib/ipfs.ts
  src/lib/storage.ts
  src/lib/storage/entities/credentialEntity.ts
  src/lib/storage/entities/derivedKeyEntity.ts
  src/lib/storage/entities/index.ts
  src/lib/storage/entities/masterKeyEntity.ts
  src/lib/storage/entities/personaEntity.ts
  src/lib/storage/entities/signatureEntity.ts
  src/lib/storage/entities/verifiableCredentialEntity.ts
  src/lib/storage/storage.ts
  src/store.ts
  src/ui/home/containers/identity.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/registration/components/seedPhrase.tsx
  src/ui/registration/containers/seedPhrase.tsx
  tests/actions/account/__snapshots__/index.test.ts.snap
  tests/actions/account/index.test.ts
  tests/actions/registration/__snapshots__/index.test.ts.snap
  tests/actions/registration/index.test.ts
  tests/lib/__snapshots__/dbHelper.test.ts.snap
  tests/lib/__snapshots__/storage.test.ts.snap
  tests/lib/dbHelper.test.ts
  tests/lib/storage.test.ts
  tsconfig.json
  webpack.haul.js
  yarn.lock
Labels: code review required, feature, finished

#1019 Feature/#1013 ui claims display
  src/actions/account/index.ts
  src/reducers/account/claims.ts
  src/reducers/account/did.ts
  src/reducers/account/index.ts
  src/resources/index.ts
  src/resources/svg/AccessibilityIcon.js
  src/resources/svg/EmailIcon.js
  src/resources/svg/MoreIcon.js
  src/resources/svg/NameIcon.js
  src/resources/svg/PhoneIcon.js
  src/routes.ts
  src/styles/jolocom-theme.ts
  src/ui/home/components/claimCard.tsx
  src/ui/home/components/claimDetails.tsx
  src/ui/home/components/claimOverview.tsx
  src/ui/home/components/identity.tsx
  src/ui/home/containers/claims.tsx
  src/ui/home/containers/identity.tsx
  src/ui/home/index.tsx
  tests/actions/account/index.test.ts
  tests/reducers/accounts/__snapshots__/index.test.ts.snap
  tests/ui/components/__snapshots__/claimCard.test.tsx.snap
  tests/ui/components/__snapshots__/claimOverview.test.tsx.snap
  tests/ui/components/__snapshots__/identity.test.tsx.snap
  tests/ui/components/claimCard.test.tsx
  tests/ui/components/claimOverview.test.tsx
  tests/ui/components/identity.test.tsx
  tests/ui/containers/__snapshots__/claims.test.tsx.snap
  tests/ui/containers/__snapshots__/identity.test.tsx.snap
  tests/ui/containers/claims.test.tsx
Labels: code review required

#1030 IPFS cat implementation
  package.json
  src/lib/ipfs.ts
  tests/lib/ipfs.test.ts
  yarn.lock
Labels: code review required, finished

#1038 Restore gradle.properties
  android/app.gradle.properties
Labels: bug, code review required

#1045 Added splash screen for loading
  package.json
  src/actions/account/index.ts
  src/actions/generic/index.ts
  src/reducers/account/did.ts
  src/reducers/account/index.ts
  src/reducers/account/loading.ts
  src/resources/img/splashScreen.png
  src/ui/generic/index.ts
  src/ui/generic/loading.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/registration/containers/passwordEntry.tsx
  tests/actions/account/__snapshots__/index.test.ts.snap
  tests/reducers/accounts/__snapshots__/index.test.ts.snap
  tests/ui/containers/__snapshots__/landing.test.tsx.snap
  tests/ui/containers/landing.test.tsx
  yarn.lock
Labels: code review required, finished

#1046 Action for consuming the QR encoded credential request, plus boilerplate for redux
  package.json
  src/actions/index.ts
  src/actions/sso/index.ts
  src/lib/storage/entities/verifiableCredentialEntity.ts
  src/lib/storage/storage.ts
  src/reducers/index.ts
  src/reducers/sso/index.ts
  src/ui/home/containers/claims.tsx
  webpack.haul.js
  yarn.lock
Labels: code review required, feature, finished
