Repository jolocom/smartwallet-app, pull requests merged in 2019-09, with the labels that each got.

#1435 move keychain pword saving to skp creation method
  src/backendMiddleware.ts
Labels: bug, code review required

#1433 SeedPhrase input
  android/app/src/main/AndroidManifest.xml
  index.ts
  package.json
  src/actions/recovery.ts
  src/actions/registration/index.ts
  src/backendMiddleware.ts
  src/locales/en.json
  src/locales/strings.ts
  src/resources/index.ts
  src/resources/svg/CheckmarkIcon.js
  src/resources/svg/NextIcon.js
  src/resources/svg/PreviousIcon.js
  src/resources/svg/SpinningIcon.js
  src/routeList.ts
  src/routes.ts
  src/styles/colors.ts
  src/styles/typography.ts
  src/ui/animation/Rotation.tsx
  src/ui/landing/components/landing.tsx
  src/ui/landing/containers/landing.tsx
  src/ui/recovery/components/inputSeedPhrase.tsx
  src/ui/recovery/container/inputSeedPhrase.tsx
  src/ui/recovery/container/repeatSeedPhrase.tsx
  src/ui/structure/transparentButton.tsx
  src/utils/asyncTimeout.ts
  tests/actions/registration/data/mockRegistrationData.ts
  tests/backendMiddleware.test.ts
  tests/ui/components/__snapshots__/inputSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/landing.test.tsx.snap
  tests/ui/components/__snapshots__/repeatSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/seedPhrase.test.tsx.snap
  tests/ui/components/inputSeedPhrase.test.tsx
  tests/ui/components/landing.test.tsx
  tests/ui/containers/__snapshots__/landing.test.tsx.snap
  tests/ui/containers/landing.test.tsx
  yarn.lock
Labels: code review required

#1445 Skipping empty fields when rendering consent screen
  src/ui/sso/components/checkboxCredential.tsx
  src/utils/filterDocuments.ts
Labels: code review required

#1432 Refactor credentials overview claimcards
  .eslintrc.js
  src/styles/jolocom-theme.android.ts
  src/styles/jolocom-theme.ios.ts
  src/styles/jolocom-theme.ts
  src/ui/home/components/collapsibleCredentialCard.tsx
  src/ui/home/components/credentialCard.tsx
  src/ui/home/components/credentialCategory.tsx
  src/ui/home/components/credentialOverview.tsx
  src/ui/home/components/interactions.tsx
  src/ui/home/components/placeholderCredentialCard.tsx
  src/ui/home/components/sharedConstants.ts
  src/ui/payment/components/paymentConsentCard.tsx
  src/ui/recovery/components/inputSeedPhrase.tsx
  src/ui/recovery/components/placeholder.tsx
  src/ui/registration/containers/progress.tsx
  src/ui/settings/components/settings.tsx
  src/ui/settings/components/settingsItem.tsx
  src/ui/sso/components/claimCard.tsx
  tests/ui/components/__snapshots__/credentialCard.test.tsx.snap
  tests/ui/components/__snapshots__/inputSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/placeholder.test.tsx.snap
  tests/ui/components/credentialCard.test.tsx
Labels: code review required

#1470 Commit process: husky + precise-commits (prettier) + commitizen
  bin/precommit.js
  package.json
  yarn.lock
Labels: code review required

#1468 GitHub action for PoEditor terms
  .github/workflows/poeditor.yml
Labels: feature

#1464 Missing Translations
  src/locales/de.json
  src/locales/nl.json
Labels: review

#1472 1459/Issuer flow on interaction screens
  src/actions/account/index.ts
  src/actions/sso/authenticationRequest.ts
  src/actions/sso/credentialOfferRequest.ts
  src/actions/sso/paymentRequest.ts
  src/actions/sso/types.ts
  src/actions/sso/utils.ts
  src/lib/storage/storage.ts
  src/reducers/sso/index.ts
  src/ui/authentication/components/authenticationConsent.tsx
  src/ui/documents/components/issuerCard.tsx
  src/ui/payment/components/paymentConsent.tsx
  tests/reducers/sso/__snapshots__/index.test.ts.snap
Labels: housekeeping, review

#1475 Housekeeping/simplify group attributes by credential
  src/lib/storage/storage.ts
  src/lib/storage/utils.ts
  tests/lib/storage.test.ts
Labels: housekeeping, review

#1473 Fix UI Bugs on iOS
  src/locales/en.json
  src/locales/strings.ts
  src/ui/recovery/components/inputSeedPhrase.tsx
  src/ui/structure/transparentButton.tsx
  tests/ui/components/__snapshots__/inputSeedPhrase.test.tsx.snap
Labels: review

#1478 Replaced the SSO reducer with navigation props
  src/actions/sso/authenticationRequest.ts
  src/actions/sso/index.ts
  src/actions/sso/paymentRequest.ts
  src/actions/sso/types.ts
  src/reducers/index.ts
  src/reducers/sso/index.ts
  src/ui/authentication/components/authenticationConsent.tsx
  src/ui/authentication/container/authenticationConsent.tsx
  src/ui/payment/components/paymentConsent.tsx
  src/ui/payment/containers/paymentConsent.tsx
  src/ui/sso/components/checkboxCredential.tsx
  src/ui/sso/components/consent.tsx
  src/ui/sso/components/credentialsSectionCard.tsx
  src/ui/sso/containers/consent.tsx
  tests/reducers/sso/__snapshots__/index.test.ts.snap
  tests/reducers/sso/index.test.ts
Labels: housekeeping, review

#1482 Refactor the settings into reusable components
  src/locales/en.json
  src/locales/strings.ts
  src/ui/settings/components/localeSetting.tsx
  src/ui/settings/components/settingItem.tsx
  src/ui/settings/components/settingSection.tsx
  src/ui/settings/components/settings.tsx
  src/ui/settings/containers/settings.tsx
Labels: housekeeping, review

#1454 Add react native storybook
  package.json
  src/routeList.ts
  src/routes.ts
  src/storybook/index.ts
  src/storybook/stories/cardWrapper.stories.tsx
  src/storybook/stories/index.tsx
  src/storybook/stories/issuerCard.stories.tsx
  src/ui/settings/containers/settings.tsx
  src/ui/storybook/index.tsx
  yarn.lock
Labels: review

#1417 E2E tests setup and initial tests
  README.md
  android/app/build.gradle
  android/app/src/androidTest/java/com/jolocomwallet/DetoxTest.java
  android/build.gradle
  e2e/01_new_user/01_landing.spec.ts
  e2e/01_new_user/02_creation.spec.ts
  e2e/01_new_user/03_recovery.spec.ts
  e2e/02_interactions/01_payment.spec.ts
  e2e/02_interactions/02_authentication.spec.ts
  e2e/02_interactions/03_credential_request.spec.ts
  e2e/02_interactions/04_credential_offer.spec.ts
  e2e/02_interactions/05_errors.spec.ts
  e2e/init.js
  e2e/jest.config.js
  e2e/utils.ts
  jest.config.js
  package.json
  src/config.ts
  src/ui/home/containers/claims.tsx
  src/ui/landing/components/landing.tsx
  src/ui/recovery/components/inputSeedPhrase.tsx
  src/ui/registration/components/entropy.tsx
  src/ui/registration/components/handAnimation.tsx
  src/ui/registration/containers/progress.tsx
  src/ui/structure/container.tsx
  tests/ui/components/__snapshots__/entropy.test.tsx.snap
  tests/ui/components/__snapshots__/inputSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/landing.test.tsx.snap
  tests/ui/containers/__snapshots__/claims.test.tsx.snap
  tsconfig.json
  yarn.lock
Labels: review
