Repository jolocom/smartwallet-app, pull requests merged in 2019-12, with the labels that each got.

#1506 Error Reporting 2.0
  android/app/build.gradle
  android/app/src/main/java/com/jolocomwallet/MainApplication.java
  android/settings.gradle
  ios/JolocomWallet.xcodeproj/project.pbxproj
  package.json
  src/config.ts
  src/lib/errors.ts
  src/locales/en.json
  src/locales/strings.ts
  src/resources/index.ts
  src/resources/svg/BackIcon.js
  src/resources/svg/CrossIcon.js
  src/resources/svg/DropdownIcon.js
  src/routeList.ts
  src/routes.ts
  src/styles/breakpoints.ts
  src/styles/colors.ts
  src/styles/config.ts
  src/ui/errors/components/chooseIssueSection.tsx
  src/ui/errors/components/contactSection.tsx
  src/ui/errors/components/descriptionSection.tsx
  src/ui/errors/components/emojiSection.tsx
  src/ui/errors/components/navigationSection.tsx
  src/ui/errors/components/sectionWrapper.tsx
  src/ui/errors/containers/errorReporting.tsx
  src/ui/errors/styles.ts
  src/ui/generic/exception.tsx
  src/ui/structure/container.tsx
  src/ui/structure/gradientButton.tsx
  src/ui/structure/toggleSwitch.tsx
  tests/__mocks__/deprecated-react-native-listview/index.js
  tests/ui/components/errors/__snapshots__/chooseIssueSection.test.tsx.snap
  tests/ui/components/errors/__snapshots__/contactSection.test.tsx.snap
  tests/ui/components/errors/__snapshots__/descriptionSection.test.tsx.snap
  tests/ui/components/errors/__snapshots__/emojiSection.test.tsx.snap
  tests/ui/components/errors/__snapshots__/navigationSection.test.tsx.snap
  tests/ui/components/errors/__snapshots__/sectionWrapper.test.tsx.snap
  tests/ui/components/errors/chooseIssueSection.test.tsx
  tests/ui/components/errors/contactSection.test.tsx
  tests/ui/components/errors/descriptionSection.test.tsx
  tests/ui/components/errors/emojiSection.test.tsx
  tests/ui/components/errors/navigationSection.test.tsx
  tests/ui/components/errors/sectionWrapper.test.tsx
  tests/ui/generic/__snapshots__/exception.test.tsx.snap
  tests/ui/generic/exception.test.tsx
  tests/ui/structure/__snapshots__/container.test.tsx.snap
  tests/ui/structure/__snapshots__/gradientButton.test.tsx.snap
  tests/ui/structure/__snapshots__/toggleSwitch.test.tsx.snap
  tests/ui/structure/gradientButton.test.tsx
  tests/ui/structure/toggleSwitch.test.tsx
  tests/utils/setup.ts
  yarn.lock
Labels: feature, review

#1492 "Add claim" UX
  package.json
  src/ui/home/components/claimDetails.tsx
  src/ui/home/components/textInputField.tsx
  tests/misc.test.ts
  tests/ui/components/__snapshots__/claimDetails.test.tsx.snap
  tests/ui/components/__snapshots__/textInputField.test.tsx.snap
  yarn.lock
Labels: review

#1513 Remove console spam
  ormconfig.ts
  src/ui/home/components/credentialCategory.tsx
  src/ui/home/components/credentialOverview.tsx
Labels: housekeeping

#1500 1499/notification backend
  src/actions/index.ts
  src/actions/modifiers.ts
  src/actions/notifications/index.ts
  src/lib/notifications.ts
  src/reducers/index.ts
  src/reducers/notifications/index.ts
  src/store.ts
  src/ui/settings/containers/settings.tsx
  tests/actions/notifications/__snapshots__/index.test.ts.snap
  tests/actions/notifications/index.test.ts
  tests/utils/createMockStore.ts
Labels: feature

#1524 build(react-native): bumped react-native to 0.59.9
  package.json
  yarn.lock
Labels: finished, review

#1525 Restrict landscape orientation on iOS and Android
  android/app/src/main/AndroidManifest.xml
  ios/JolocomWallet/Base.lproj/Info.plist
Labels: finished, review

#1523 LinearGradient in JoloButton
  src/styles/buttons.ts
  src/ui/errors/containers/errorReporting.tsx
  src/ui/generic/exception.tsx
  src/ui/home/components/claimDetails.tsx
  src/ui/landing/components/landing.tsx
  src/ui/recovery/components/repeatSeedPhrase.tsx
  src/ui/recovery/components/seedPhrase.tsx
  src/ui/structure/jolocomButton.tsx
  tests/ui/components/__snapshots__/claimDetails.test.tsx.snap
  tests/ui/components/__snapshots__/inputSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/landing.test.tsx.snap
  tests/ui/components/__snapshots__/repeatSeedPhrase.test.tsx.snap
  tests/ui/components/__snapshots__/seedPhrase.test.tsx.snap
  tests/ui/generic/__snapshots__/exception.test.tsx.snap
Labels: finished, review
